
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Bbox.java
//  @ Date : 24/09/2018
//  @ Author : 
//
//


import java.awt.Point;
import javax.media.opengl.*;

public class Bbox { // BoundingRectangulo

    private GL gl;
    
    private Point P1;
    private Point P2;
    
    public void BBox(GL gl) {
        this.gl = gl;
    }            

    public Bbox(GL gl) {
        this(gl, new Point(0, 0), new Point(0, 0));
    }

    public Bbox(GL gl, Point P1, Point P2) {
        //super(gl);
        this.P1 = P1;
        this.P2 = P2;
    }

    public void desenha() {
        //super.desenha();
        gl.glColor3f(r, g, b);

        GL gl = getGL();
        gl.glBegin(GL.GL_LINE_LOOP);
        gl.glVertex2f((float)P1.getX(), (float)P1.getY());
        gl.glVertex2f((float)P1.getX(), (float)P2.getY());
        gl.glVertex2f((float)P2.getX(), (float)P2.getY());
        gl.glVertex2f((float)P2.getX(), (float)P1.getY());
        gl.glEnd();
    }

    @Override
    public void insereEm(ObjetoGrafico objG) {
        if(objG instanceof BoundingCircle) {
            BoundingCircle bC = (BoundingCircle) objG;
            Point pts[] = bC.getRectanglePoints();
            P1 = pts[0];
            P2 = pts[1];
        }
    }

    @Override
    public boolean dentroDoLimite(Point P) {
        System.out.println("Ponto limite = " + P);
        System.out.println("P1 = " + P1);
        System.out.println("P2 = " + P2);
        if(P.getX() > P1.getX() && P.getY() > P1.getY() && P.getX() < P2.getX() && P.getY() < P2.getY()) {
           return true;
        }
        return false;
    }

}