//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Camera.java
//  @ Date : 24/09/2018
//  @ Author : 
//
//




public class Camera {
	public Object xMinimo = 0;
	public Object xMaximo = 400;
	public Object yMinimo = 400;
	public Object yMaximo = 0;
	public void Zoom() {
	
	}
	
	public void Pan() {
	
	}
	
	public void Ortho2D(Object xMinimo, Object xMaximo, Object yMinimo, Object yMaximo) {
	
	}
}
