
//
//

import java.util.ArrayList;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Mundo.java
//  @ Date : 24/09/2018
//  @ Author : 
//
//




public class Mundo {
    
	public Poligono poligonoSelecionador; //= topoLista;
	public ArrayList<Poligono> listaPoligonos;
}
