
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Poligono.java
//  @ Date : 24/09/2018
//  @ Author : 
//
//




public class Poligono extends ObjetoGrafico {
	public Object primitiva; // = Line_Loop;
	public Object cor;
}
