//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ponto4D.java
//  @ Date : 24/09/2018
//  @ Author : 
//
//




public class Ponto4D {
	public Object x;
	public Object y;
}
